const CONTAINER_OPS = Object.freeze(["inspect", "move", "resize", "width", "height", "hide", "show"]);
const LABEL_OPS = Object.freeze(["inspect", "move", "width", "hide", "show"]);
const CONTROL_OPS = Object.freeze(["inspect", "move", "width", "height", "hide", "show"]);
const ACTION_CONTROL_OPS = Object.freeze(["inspect", "move", "width", "height", "hide", "show"]);
const ACTION_OPS = Object.freeze(["inspect", "show", "hide", "move"]);
const INSPECT_OPS = Object.freeze(["inspect"]);
const CONTROL_LOCKED_OPS = Object.freeze(["rename"]);
const ACTION_CONTROL_LOCKED_OPS = Object.freeze(["resize", "rename"]);

const ROOT_OPS = CONTAINER_OPS;
const AREA_OPS = CONTAINER_OPS;
const GROUP_OPS = CONTAINER_OPS;
const FIELD_OPS = CONTAINER_OPS;
const BUTTON_OPS = ACTION_OPS;
const LIST_OPS = CONTAINER_OPS;
const CARD_OPS = CONTAINER_OPS;
const STATUS_OPS = LABEL_OPS;

const META = Object.freeze({
  container: Object.freeze({
    editGranularity: "container",
    previewTargetMode: "self",
    affectsContainer: true,
  }),
  element: Object.freeze({
    editGranularity: "element",
    previewTargetMode: "self",
    affectsContainer: false,
  }),
  control: Object.freeze({
    editGranularity: "control",
    previewTargetMode: "self",
    affectsContainer: false,
  }),
});

function createRegistryEntry({
  id,
  name,
  type,
  role,
  parentId,
  order,
  allowedOps,
  lockedOps = [],
  metadata = {},
}) {
  const safeAllowedOps = [...allowedOps];
  const safeLockedOps = [...lockedOps];
  return Object.freeze({
    id,
    name,
    type,
    role,
    parentId,
    order,
    visible: true,
    editable: safeAllowedOps.length > 0,
    allowedOps: safeAllowedOps,
    lockedOps: safeLockedOps,
    ...metadata,
  });
}

const RESTARBEITEN_MAIN_UI_REGISTRY = Object.freeze([
  createRegistryEntry({
    id: "restarbeiten.root",
    name: "Restarbeiten",
    type: "root",
    role: "system",
    parentId: null,
    order: 1,
    allowedOps: ROOT_OPS,
  }),

  createRegistryEntry({
    id: "restarbeiten.quicklane",
    name: "Quicklane",
    type: "toolbar",
    role: "layout",
    parentId: "restarbeiten.root",
    order: 10,
    allowedOps: AREA_OPS,
  }),
  createRegistryEntry({
    id: "restarbeiten.quicklane.group.navigation",
    name: "Quicklane Navigation",
    type: "group",
    role: "navigation",
    parentId: "restarbeiten.quicklane",
    order: 10,
    allowedOps: GROUP_OPS,
  }),
  createRegistryEntry({
    id: "restarbeiten.quicklane.pin",
    name: "Fixieren",
    type: "button",
    role: "navigation",
    parentId: "restarbeiten.quicklane.group.navigation",
    order: 10,
    allowedOps: BUTTON_OPS,
  }),
  createRegistryEntry({
    id: "restarbeiten.quicklane.action.project",
    name: "Projekt",
    type: "button",
    role: "navigation",
    parentId: "restarbeiten.quicklane.group.navigation",
    order: 20,
    allowedOps: BUTTON_OPS,
  }),
  createRegistryEntry({
    id: "restarbeiten.quicklane.action.firms",
    name: "Firmen",
    type: "button",
    role: "navigation",
    parentId: "restarbeiten.quicklane.group.navigation",
    order: 30,
    allowedOps: BUTTON_OPS,
  }),
  createRegistryEntry({
    id: "restarbeiten.quicklane.group.visibility",
    name: "Quicklane Anzeige",
    type: "group",
    role: "visibility",
    parentId: "restarbeiten.quicklane",
    order: 20,
    allowedOps: GROUP_OPS,
  }),
  createRegistryEntry({
    id: "restarbeiten.quicklane.action.ampel",
    name: "Ampel",
    type: "button",
    role: "visibility",
    parentId: "restarbeiten.quicklane.group.visibility",
    order: 10,
    allowedOps: BUTTON_OPS,
  }),
  createRegistryEntry({
    id: "restarbeiten.quicklane.action.longtext",
    name: "Langtext",
    type: "button",
    role: "visibility",
    parentId: "restarbeiten.quicklane.group.visibility",
    order: 20,
    allowedOps: BUTTON_OPS,
  }),
  createRegistryEntry({
    id: "restarbeiten.quicklane.group.output",
    name: "Quicklane Ausgabe",
    type: "group",
    role: "action",
    parentId: "restarbeiten.quicklane",
    order: 30,
    allowedOps: GROUP_OPS,
  }),
  createRegistryEntry({
    id: "restarbeiten.quicklane.action.pdfPreview",
    name: "PDF Voransicht",
    type: "button",
    role: "action",
    parentId: "restarbeiten.quicklane.group.output",
    order: 10,
    allowedOps: BUTTON_OPS,
  }),
  createRegistryEntry({
    id: "restarbeiten.quicklane.output.print",
    name: "Drucken",
    type: "button",
    role: "action",
    parentId: "restarbeiten.quicklane.group.output",
    order: 20,
    allowedOps: BUTTON_OPS,
  }),
  createRegistryEntry({
    id: "restarbeiten.quicklane.output.email",
    name: "E-Mail",
    type: "button",
    role: "action",
    parentId: "restarbeiten.quicklane.group.output",
    order: 30,
    allowedOps: BUTTON_OPS,
  }),

  createRegistryEntry({
    id: "restarbeiten.filterbar",
    name: "Filterleiste",
    type: "toolbar",
    role: "layout",
    parentId: "restarbeiten.root",
    order: 20,
    allowedOps: AREA_OPS,
  }),
  createRegistryEntry({
    id: "restarbeiten.filterbar.group.location",
    name: "Verortung",
    type: "group",
    role: "layout",
    parentId: "restarbeiten.filterbar",
    order: 10,
    allowedOps: GROUP_OPS,
  }),
  createRegistryEntry({
    id: "restarbeiten.filterbar.location.level1",
    name: "Verortung L1",
    type: "field",
    role: "meta",
    parentId: "restarbeiten.filterbar.group.location",
    order: 10,
    allowedOps: FIELD_OPS,
  }),
  createRegistryEntry({
    id: "restarbeiten.filterbar.location.level1.label",
    name: "Haus",
    type: "label",
    role: "meta",
    parentId: "restarbeiten.filterbar.location.level1",
    order: 5,
    allowedOps: LABEL_OPS,
  }),
  createRegistryEntry({
    id: "restarbeiten.filterbar.location.level2",
    name: "Verortung L2",
    type: "field",
    role: "meta",
    parentId: "restarbeiten.filterbar.group.location",
    order: 20,
    allowedOps: FIELD_OPS,
  }),
  createRegistryEntry({
    id: "restarbeiten.filterbar.location.level2.label",
    name: "Geschoss",
    type: "label",
    role: "meta",
    parentId: "restarbeiten.filterbar.location.level2",
    order: 5,
    allowedOps: LABEL_OPS,
  }),
  createRegistryEntry({
    id: "restarbeiten.filterbar.location.level3",
    name: "Verortung L3",
    type: "field",
    role: "meta",
    parentId: "restarbeiten.filterbar.group.location",
    order: 30,
    allowedOps: FIELD_OPS,
  }),
  createRegistryEntry({
    id: "restarbeiten.filterbar.location.level3.label",
    name: "Einheit",
    type: "label",
    role: "meta",
    parentId: "restarbeiten.filterbar.location.level3",
    order: 5,
    allowedOps: LABEL_OPS,
  }),
  createRegistryEntry({
    id: "restarbeiten.filterbar.location.level4",
    name: "Verortung L4",
    type: "field",
    role: "meta",
    parentId: "restarbeiten.filterbar.group.location",
    order: 40,
    allowedOps: FIELD_OPS,
  }),
  createRegistryEntry({
    id: "restarbeiten.filterbar.location.level4.label",
    name: "Raum",
    type: "label",
    role: "meta",
    parentId: "restarbeiten.filterbar.location.level4",
    order: 5,
    allowedOps: LABEL_OPS,
  }),
  createRegistryEntry({
    id: "restarbeiten.filterbar.group.class",
    name: "Klasse",
    type: "group",
    role: "layout",
    parentId: "restarbeiten.filterbar",
    order: 20,
    allowedOps: GROUP_OPS,
  }),
  createRegistryEntry({
    id: "restarbeiten.filterbar.class.all",
    name: "Alle",
    type: "button",
    role: "visibility",
    parentId: "restarbeiten.filterbar.group.class",
    order: 10,
    allowedOps: BUTTON_OPS,
  }),
  createRegistryEntry({
    id: "restarbeiten.filterbar.class.rest",
    name: "Restarbeit",
    type: "button",
    role: "visibility",
    parentId: "restarbeiten.filterbar.group.class",
    order: 20,
    allowedOps: BUTTON_OPS,
  }),
  createRegistryEntry({
    id: "restarbeiten.filterbar.class.defect",
    name: "Mangel",
    type: "button",
    role: "visibility",
    parentId: "restarbeiten.filterbar.group.class",
    order: 30,
    allowedOps: BUTTON_OPS,
  }),
  createRegistryEntry({
    id: "restarbeiten.filterbar.group.meta",
    name: "Meta",
    type: "group",
    role: "layout",
    parentId: "restarbeiten.filterbar",
    order: 30,
    allowedOps: GROUP_OPS,
  }),
  createRegistryEntry({
    id: "restarbeiten.filterbar.meta.status",
    name: "Status",
    type: "field",
    role: "status",
    parentId: "restarbeiten.filterbar.group.meta",
    order: 10,
    allowedOps: FIELD_OPS,
  }),
  createRegistryEntry({
    id: "restarbeiten.filterbar.meta.status.label",
    name: "Status",
    type: "label",
    role: "meta",
    parentId: "restarbeiten.filterbar.meta.status",
    order: 5,
    allowedOps: LABEL_OPS,
  }),
  createRegistryEntry({
    id: "restarbeiten.filterbar.meta.dueDate",
    name: "Fertig bis",
    type: "field",
    role: "date",
    parentId: "restarbeiten.filterbar.group.meta",
    order: 20,
    allowedOps: FIELD_OPS,
  }),
  createRegistryEntry({
    id: "restarbeiten.filterbar.meta.dueDate.label",
    name: "Fertig bis",
    type: "label",
    role: "meta",
    parentId: "restarbeiten.filterbar.meta.dueDate",
    order: 5,
    allowedOps: LABEL_OPS,
  }),
  createRegistryEntry({
    id: "restarbeiten.filterbar.meta.responsible",
    name: "Verantwortlich",
    type: "field",
    role: "responsible",
    parentId: "restarbeiten.filterbar.group.meta",
    order: 30,
    allowedOps: FIELD_OPS,
  }),
  createRegistryEntry({
    id: "restarbeiten.filterbar.meta.responsible.label",
    name: "Verantwortlich",
    type: "label",
    role: "meta",
    parentId: "restarbeiten.filterbar.meta.responsible",
    order: 5,
    allowedOps: LABEL_OPS,
  }),
  createRegistryEntry({
    id: "restarbeiten.filterbar.actions",
    name: "Filter-Aktionen",
    type: "group",
    role: "layout",
    parentId: "restarbeiten.filterbar",
    order: 40,
    allowedOps: GROUP_OPS,
  }),
  createRegistryEntry({
    id: "restarbeiten.filterbar.action.close",
    name: "Beenden / Schliessen",
    type: "button",
    role: "navigation",
    parentId: "restarbeiten.filterbar.actions",
    order: 10,
    allowedOps: BUTTON_OPS,
  }),

  createRegistryEntry({
    id: "restarbeiten.main",
    name: "Hauptbereich",
    type: "area",
    role: "layout",
    parentId: "restarbeiten.root",
    order: 30,
    allowedOps: AREA_OPS,
  }),
  createRegistryEntry({
    id: "restarbeiten.main.sheet",
    name: "Blattansicht",
    type: "component",
    role: "layout",
    parentId: "restarbeiten.main",
    order: 10,
    allowedOps: GROUP_OPS,
  }),
  createRegistryEntry({
    id: "restarbeiten.main.sheet.paper",
    name: "Blatt",
    type: "componentPart",
    role: "layout",
    parentId: "restarbeiten.main.sheet",
    order: 10,
    allowedOps: GROUP_OPS,
  }),
  createRegistryEntry({
    id: "restarbeiten.main.tableHeader",
    name: "Tabellenkopf",
    type: "componentPart",
    role: "structure",
    parentId: "restarbeiten.main.sheet.paper",
    order: 20,
    allowedOps: GROUP_OPS,
  }),
  createRegistryEntry({
    id: "restarbeiten.main.tableHeader.number",
    name: "Nr.",
    type: "label",
    role: "structure",
    parentId: "restarbeiten.main.tableHeader",
    order: 10,
    allowedOps: LABEL_OPS,
  }),
  createRegistryEntry({
    id: "restarbeiten.main.tableHeader.subject",
    name: "Gegenstand",
    type: "label",
    role: "structure",
    parentId: "restarbeiten.main.tableHeader",
    order: 20,
    allowedOps: LABEL_OPS,
  }),
  createRegistryEntry({
    id: "restarbeiten.main.tableHeader.dueDate",
    name: "Fertig bis",
    type: "label",
    role: "date",
    parentId: "restarbeiten.main.tableHeader",
    order: 30,
    allowedOps: LABEL_OPS,
  }),
  createRegistryEntry({
    id: "restarbeiten.main.tableHeader.status",
    name: "Status",
    type: "label",
    role: "status",
    parentId: "restarbeiten.main.tableHeader",
    order: 40,
    allowedOps: LABEL_OPS,
  }),
  createRegistryEntry({
    id: "restarbeiten.main.tableHeader.responsible",
    name: "Verantw.",
    type: "label",
    role: "responsible",
    parentId: "restarbeiten.main.tableHeader",
    order: 50,
    allowedOps: LABEL_OPS,
  }),
  createRegistryEntry({
    id: "restarbeiten.main.records",
    name: "Datensaetze",
    type: "list",
    role: "content",
    parentId: "restarbeiten.main.sheet.paper",
    order: 30,
    allowedOps: LIST_OPS,
  }),

  createRegistryEntry({
    id: "restarbeiten.record",
    name: "Restarbeiten-Datensatz",
    type: "card",
    role: "content",
    parentId: "restarbeiten.main.records",
    order: 10,
    allowedOps: CARD_OPS,
  }),
  createRegistryEntry({
    id: "restarbeiten.record.numberColumn",
    name: "Nummern-Spalte",
    type: "componentPart",
    role: "structure",
    parentId: "restarbeiten.record",
    order: 10,
    allowedOps: GROUP_OPS,
  }),
  createRegistryEntry({
    id: "restarbeiten.record.number",
    name: "Laufende Nummer",
    type: "label",
    role: "structure",
    parentId: "restarbeiten.record.numberColumn",
    order: 10,
    allowedOps: LABEL_OPS,
  }),
  createRegistryEntry({
    id: "restarbeiten.record.createdAt",
    name: "Erfassungsdatum",
    type: "label",
    role: "date",
    parentId: "restarbeiten.record.numberColumn",
    order: 20,
    allowedOps: LABEL_OPS,
  }),
  createRegistryEntry({
    id: "restarbeiten.record.itemClass",
    name: "Klasse",
    type: "label",
    role: "status",
    parentId: "restarbeiten.record.numberColumn",
    order: 30,
    allowedOps: LABEL_OPS,
  }),
  createRegistryEntry({
    id: "restarbeiten.record.photos",
    name: "Fotos",
    type: "button",
    role: "action",
    parentId: "restarbeiten.record.numberColumn",
    order: 40,
    allowedOps: BUTTON_OPS,
  }),
  createRegistryEntry({
    id: "restarbeiten.record.contentColumn",
    name: "Inhaltsspalte",
    type: "componentPart",
    role: "content",
    parentId: "restarbeiten.record",
    order: 20,
    allowedOps: GROUP_OPS,
  }),
  createRegistryEntry({
    id: "restarbeiten.record.location",
    name: "Verortung",
    type: "label",
    role: "meta",
    parentId: "restarbeiten.record.contentColumn",
    order: 10,
    allowedOps: LABEL_OPS,
  }),
  createRegistryEntry({
    id: "restarbeiten.record.shortText",
    name: "Kurztext",
    type: "label",
    role: "content",
    parentId: "restarbeiten.record.contentColumn",
    order: 20,
    allowedOps: LABEL_OPS,
  }),
  createRegistryEntry({
    id: "restarbeiten.record.longText",
    name: "Langtext",
    type: "label",
    role: "content",
    parentId: "restarbeiten.record.contentColumn",
    order: 30,
    allowedOps: LABEL_OPS,
  }),
  createRegistryEntry({
    id: "restarbeiten.record.metaColumn",
    name: "Metaspalte",
    type: "componentPart",
    role: "meta",
    parentId: "restarbeiten.record",
    order: 30,
    allowedOps: GROUP_OPS,
  }),
  createRegistryEntry({
    id: "restarbeiten.record.dueDate",
    name: "Fertig bis",
    type: "label",
    role: "date",
    parentId: "restarbeiten.record.metaColumn",
    order: 10,
    allowedOps: LABEL_OPS,
  }),
  createRegistryEntry({
    id: "restarbeiten.record.ampel",
    name: "Ampel",
    type: "statusIndicator",
    role: "status",
    parentId: "restarbeiten.record.metaColumn",
    order: 20,
    allowedOps: STATUS_OPS,
  }),
  createRegistryEntry({
    id: "restarbeiten.record.status",
    name: "Status",
    type: "label",
    role: "status",
    parentId: "restarbeiten.record.metaColumn",
    order: 30,
    allowedOps: LABEL_OPS,
  }),
  createRegistryEntry({
    id: "restarbeiten.record.responsible",
    name: "Verantwortlich",
    type: "label",
    role: "responsible",
    parentId: "restarbeiten.record.metaColumn",
    order: 40,
    allowedOps: LABEL_OPS,
  }),

  createRegistryEntry({
    id: "restarbeiten.editbox",
    name: "Editbox",
    type: "area",
    role: "layout",
    parentId: "restarbeiten.root",
    order: 40,
    allowedOps: AREA_OPS,
  }),
  createRegistryEntry({
    id: "restarbeiten.editbox.header",
    name: "Editbox-Kopf",
    type: "componentPart",
    role: "layout",
    parentId: "restarbeiten.editbox",
    order: 10,
    allowedOps: GROUP_OPS,
    metadata: META.container,
  }),
  createRegistryEntry({
    id: "restarbeiten.editbox.header.currentRecord",
    name: "Aktueller Datensatz",
    type: "label",
    role: "structure",
    parentId: "restarbeiten.editbox.header",
    order: 10,
    allowedOps: LABEL_OPS,
    metadata: META.element,
  }),
  createRegistryEntry({
    id: "restarbeiten.editbox.action.new",
    name: "Neu",
    type: "button",
    role: "action",
    parentId: "restarbeiten.editbox.text.short",
    order: 20,
    allowedOps: ACTION_CONTROL_OPS,
    lockedOps: ACTION_CONTROL_LOCKED_OPS,
    metadata: META.control,
  }),
  createRegistryEntry({
    id: "restarbeiten.editbox.action.delete",
    name: "Löschen",
    type: "button",
    role: "action",
    parentId: "restarbeiten.editbox.text.short",
    order: 40,
    allowedOps: ACTION_CONTROL_OPS,
    lockedOps: ACTION_CONTROL_LOCKED_OPS,
    metadata: META.control,
  }),
  createRegistryEntry({
    id: "restarbeiten.editbox.text.short",
    name: "Kurztext",
    type: "field",
    role: "content",
    parentId: "restarbeiten.editbox",
    order: 20,
    allowedOps: FIELD_OPS,
    metadata: META.container,
  }),
  createRegistryEntry({
    id: "restarbeiten.editbox.text.short.label",
    name: "Kurztext / Gegenstand",
    type: "label",
    role: "content",
    parentId: "restarbeiten.editbox.text.short",
    order: 5,
    allowedOps: LABEL_OPS,
    metadata: META.element,
  }),
  createRegistryEntry({
    id: "restarbeiten.editbox.text.short.input",
    name: "Kurztext-Eingabe",
    type: "field",
    role: "content",
    parentId: "restarbeiten.editbox.text.short",
    order: 10,
    allowedOps: CONTROL_OPS,
    lockedOps: CONTROL_LOCKED_OPS,
    metadata: META.control,
  }),
  createRegistryEntry({
    id: "restarbeiten.editbox.text.short.dictation",
    name: "Diktat Kurztext",
    type: "button",
    role: "action",
    parentId: "restarbeiten.editbox.text.short",
    order: 12,
    allowedOps: ACTION_CONTROL_OPS,
    lockedOps: ACTION_CONTROL_LOCKED_OPS,
    metadata: META.control,
  }),
  createRegistryEntry({
    id: "restarbeiten.editbox.text.short.remaining",
    name: "Restzeichen Kurztext",
    type: "label",
    role: "structure",
    parentId: "restarbeiten.editbox.text.short",
    order: 15,
    allowedOps: LABEL_OPS,
    metadata: META.element,
  }),
  createRegistryEntry({
    id: "restarbeiten.editbox.text.long",
    name: "Langtext",
    type: "field",
    role: "content",
    parentId: "restarbeiten.editbox",
    order: 30,
    allowedOps: FIELD_OPS,
    metadata: META.container,
  }),
  createRegistryEntry({
    id: "restarbeiten.editbox.text.long.label",
    name: "Langtext / Beschreibung",
    type: "label",
    role: "content",
    parentId: "restarbeiten.editbox.text.long",
    order: 5,
    allowedOps: LABEL_OPS,
    metadata: META.element,
  }),
  createRegistryEntry({
    id: "restarbeiten.editbox.text.long.input",
    name: "Langtext-Eingabe",
    type: "field",
    role: "content",
    parentId: "restarbeiten.editbox.text.long",
    order: 10,
    allowedOps: CONTROL_OPS,
    lockedOps: CONTROL_LOCKED_OPS,
    metadata: META.control,
  }),
  createRegistryEntry({
    id: "restarbeiten.editbox.text.long.dictation",
    name: "Diktat Langtext",
    type: "button",
    role: "action",
    parentId: "restarbeiten.editbox.text.long",
    order: 12,
    allowedOps: ACTION_CONTROL_OPS,
    lockedOps: ACTION_CONTROL_LOCKED_OPS,
    metadata: META.control,
  }),
  createRegistryEntry({
    id: "restarbeiten.editbox.text.long.remaining",
    name: "Restzeichen Langtext",
    type: "label",
    role: "structure",
    parentId: "restarbeiten.editbox.text.long",
    order: 15,
    allowedOps: LABEL_OPS,
    metadata: META.element,
  }),
  createRegistryEntry({
    id: "restarbeiten.editbox.location",
    name: "Editbox-Verortung",
    type: "group",
    role: "layout",
    parentId: "restarbeiten.editbox",
    order: 40,
    allowedOps: GROUP_OPS,
    metadata: META.container,
  }),
  createRegistryEntry({
    id: "restarbeiten.editbox.location.level1",
    name: "L1",
    type: "field",
    role: "meta",
    parentId: "restarbeiten.editbox.location",
    order: 10,
    allowedOps: FIELD_OPS,
    metadata: META.container,
  }),
  createRegistryEntry({
    id: "restarbeiten.editbox.location.level1.label",
    name: "Haus",
    type: "label",
    role: "meta",
    parentId: "restarbeiten.editbox.location.level1",
    order: 5,
    allowedOps: LABEL_OPS,
    metadata: META.element,
  }),
  createRegistryEntry({
    id: "restarbeiten.editbox.location.level2",
    name: "L2",
    type: "field",
    role: "meta",
    parentId: "restarbeiten.editbox.location",
    order: 20,
    allowedOps: FIELD_OPS,
    metadata: META.container,
  }),
  createRegistryEntry({
    id: "restarbeiten.editbox.location.level2.label",
    name: "Geschoss",
    type: "label",
    role: "meta",
    parentId: "restarbeiten.editbox.location.level2",
    order: 5,
    allowedOps: LABEL_OPS,
    metadata: META.element,
  }),
  createRegistryEntry({
    id: "restarbeiten.editbox.location.level3",
    name: "L3",
    type: "field",
    role: "meta",
    parentId: "restarbeiten.editbox.location",
    order: 30,
    allowedOps: FIELD_OPS,
    metadata: META.container,
  }),
  createRegistryEntry({
    id: "restarbeiten.editbox.location.level3.label",
    name: "Einheit",
    type: "label",
    role: "meta",
    parentId: "restarbeiten.editbox.location.level3",
    order: 5,
    allowedOps: LABEL_OPS,
    metadata: META.element,
  }),
  createRegistryEntry({
    id: "restarbeiten.editbox.location.level4",
    name: "L4",
    type: "field",
    role: "meta",
    parentId: "restarbeiten.editbox.location",
    order: 40,
    allowedOps: FIELD_OPS,
    metadata: META.container,
  }),
  createRegistryEntry({
    id: "restarbeiten.editbox.location.level4.label",
    name: "Raum",
    type: "label",
    role: "meta",
    parentId: "restarbeiten.editbox.location.level4",
    order: 5,
    allowedOps: LABEL_OPS,
    metadata: META.element,
  }),
  createRegistryEntry({
    id: "restarbeiten.editbox.meta",
    name: "Editbox-Meta",
    type: "group",
    role: "meta",
    parentId: "restarbeiten.editbox",
    order: 50,
    allowedOps: GROUP_OPS,
    metadata: META.container,
  }),
  createRegistryEntry({
    id: "restarbeiten.editbox.meta.itemClass",
    name: "Klasse",
    type: "field",
    role: "meta",
    parentId: "restarbeiten.editbox.text.short",
    order: 30,
    allowedOps: FIELD_OPS,
    metadata: META.container,
  }),
  createRegistryEntry({
    id: "restarbeiten.editbox.meta.itemClass.label",
    name: "Klasse",
    type: "label",
    role: "meta",
    parentId: "restarbeiten.editbox.meta.itemClass",
    order: 5,
    allowedOps: LABEL_OPS,
    metadata: META.element,
  }),
  createRegistryEntry({
    id: "restarbeiten.editbox.meta.status",
    name: "Status",
    type: "field",
    role: "status",
    parentId: "restarbeiten.editbox.meta",
    order: 20,
    allowedOps: FIELD_OPS,
    metadata: META.container,
  }),
  createRegistryEntry({
    id: "restarbeiten.editbox.meta.status.label",
    name: "Status",
    type: "label",
    role: "meta",
    parentId: "restarbeiten.editbox.meta.status",
    order: 5,
    allowedOps: LABEL_OPS,
    metadata: META.element,
  }),
  createRegistryEntry({
    id: "restarbeiten.editbox.meta.dueDate",
    name: "Fertig bis",
    type: "field",
    role: "date",
    parentId: "restarbeiten.editbox.meta",
    order: 30,
    allowedOps: FIELD_OPS,
    metadata: META.container,
  }),
  createRegistryEntry({
    id: "restarbeiten.editbox.meta.dueDate.label",
    name: "Fertig bis",
    type: "label",
    role: "meta",
    parentId: "restarbeiten.editbox.meta.dueDate",
    order: 5,
    allowedOps: LABEL_OPS,
    metadata: META.element,
  }),
  createRegistryEntry({
    id: "restarbeiten.editbox.meta.responsible",
    name: "Verantwortlich",
    type: "field",
    role: "responsible",
    parentId: "restarbeiten.editbox.meta",
    order: 40,
    allowedOps: FIELD_OPS,
    metadata: META.container,
  }),
  createRegistryEntry({
    id: "restarbeiten.editbox.meta.responsible.label",
    name: "Verantwortlich",
    type: "label",
    role: "meta",
    parentId: "restarbeiten.editbox.meta.responsible",
    order: 5,
    allowedOps: LABEL_OPS,
    metadata: META.element,
  }),
  createRegistryEntry({
    id: "restarbeiten.editbox.validation.shortText",
    name: "Kurztext erforderlich",
    type: "label",
    role: "structure",
    parentId: "restarbeiten.editbox.meta",
    order: 45,
    allowedOps: LABEL_OPS,
    metadata: META.element,
  }),
  createRegistryEntry({
    id: "restarbeiten.editbox.meta.ampel",
    name: "Ampel",
    type: "statusIndicator",
    role: "status",
    parentId: "restarbeiten.editbox.meta",
    order: 50,
    allowedOps: STATUS_OPS,
    metadata: META.element,
  }),
  createRegistryEntry({
    id: "restarbeiten.editbox.meta.noteButton",
    name: "Notiz",
    type: "button",
    role: "action",
    parentId: "restarbeiten.editbox.meta",
    order: 60,
    allowedOps: ACTION_CONTROL_OPS,
    lockedOps: ACTION_CONTROL_LOCKED_OPS,
    metadata: META.control,
  }),
]);

export function getRestarbeitenMainUiRegistry() {
  return RESTARBEITEN_MAIN_UI_REGISTRY.map((entry) => ({
    ...entry,
    allowedOps: [...entry.allowedOps],
    lockedOps: [...entry.lockedOps],
  }));
}
