export function createUiInspectorOverlay(options = {}) {
  const selector = '[data-ui-inspector-id]';
  const zIndex = Number.isFinite(options.zIndex) ? String(options.zIndex) : '2147483000';
  let rootElement = null; let overlayRoot = null; let selectedTargetKey = ''; let selectedId = ''; let selectedLabel = '';
  let captureHost = null; let captureHandler = null; let targets = []; let resolveTargetByKey = null;

  const clearOverlayChildren = () => overlayRoot?.replaceChildren();
  function ensureOverlayRoot(doc) { if (overlayRoot?.isConnected) return overlayRoot; overlayRoot = doc.createElement('div'); overlayRoot.setAttribute('data-ui-inspector-overlay-root', 'true'); Object.assign(overlayRoot.style,{position:'fixed',inset:'0',pointerEvents:'none',zIndex,overflow:'hidden'}); return overlayRoot; }
  const createBadge = (doc) => { const b = doc.createElement('div'); b.setAttribute('data-ui-inspector-selection-badge','true'); Object.assign(b.style,{position:'fixed',right:'12px',top:'12px',background:'rgba(30, 35, 45, 0.92)',color:'#fff',font:'12px/1.3 monospace',padding:'6px 8px',borderRadius:'4px',pointerEvents:'none'}); b.textContent = `Auswahl: ${selectedLabel || selectedId || '-'}`; return b; };
  function createFrame(doc, target, rect) { const f=doc.createElement('div'); f.setAttribute('data-ui-inspector-overlay-frame', target.key); f.setAttribute('data-ui-inspector-overlay-id', target.id); Object.assign(f.style,{position:'fixed',left:`${rect.left}px`,top:`${rect.top}px`,width:`${rect.width}px`,height:`${rect.height}px`,boxSizing:'border-box',border:selectedTargetKey===target.key?'2px solid rgba(255, 168, 42, 0.98)':'1px solid rgba(43, 157, 255, 0.95)',background:selectedTargetKey===target.key?'rgba(255, 168, 42, 0.16)':'rgba(43, 157, 255, 0.08)',pointerEvents:'none'}); if (selectedTargetKey===target.key) f.setAttribute('data-ui-inspector-selected','true'); const l=doc.createElement('div'); l.textContent = target.label || target.id; Object.assign(l.style,{position:'absolute',left:'0',top:'-16px',maxWidth:'320px',whiteSpace:'nowrap',overflow:'hidden',textOverflow:'ellipsis',background:selectedTargetKey===target.key?'rgba(255, 168, 42, 0.98)':'rgba(43, 157, 255, 0.95)',color:'#fff',font:'11px/1.2 monospace',padding:'2px 4px',pointerEvents:'none'}); f.append(l); return f; }
  function getHitsAtPoint(x,y){return targets.filter((t)=>{const r=t.element?.getBoundingClientRect?.(); if(!r||r.width<=0||r.height<=0)return false; return !(x<r.left||x>r.left+r.width||y<r.top||y>r.top+r.height);}).map((t,idx)=>({target:t,area:t.element.getBoundingClientRect().width*t.element.getBoundingClientRect().height,depth:t.id.split('.').length,index:idx})).sort((a,b)=>a.area-b.area||b.depth-a.depth||a.index-b.index);}
  const removeHitList = ()=>{ for(const c of Array.from(overlayRoot?.children||[])){if(c?.getAttribute?.('data-ui-inspector-hit-list')==='true') c.parentElement?.removeChild?.(c);} };
  function selectTarget(target){ selectedTargetKey=String(target?.key||'').trim(); selectedId=String(target?.id||'').trim(); selectedLabel=String(target?.label||'').trim(); removeHitList(); options.onSelectTarget?.(target); options.onSelect?.(selectedId); return refresh(); }
  function clearSelection(){ selectedTargetKey=''; selectedId=''; selectedLabel=''; removeHitList(); options.onClearSelection?.(); return refresh(); }
  function showHitListAtPoint(x,y){ if(!overlayRoot||!rootElement) return false; removeHitList(); const hits=getHitsAtPoint(x,y); if(!hits.length){clearSelection(); return false;} const doc=rootElement.ownerDocument||globalThis.document; const list=doc.createElement('div'); list.setAttribute('data-ui-inspector-hit-list','true'); Object.assign(list.style,{position:'fixed',left:`${x}px`,top:`${y}px`,maxWidth:'380px',background:'rgba(24, 29, 38, 0.97)',border:'1px solid rgba(255,255,255,0.2)',borderRadius:'6px',padding:'6px',display:'flex',flexDirection:'column',gap:'4px',pointerEvents:'auto'}); for(const hit of hits){const o=doc.createElement('button'); o.type='button'; o.setAttribute('data-ui-inspector-hit-option',hit.target.key); o.textContent = `${hit.target.id}${hit.target.label?.includes('#') ? ` (${hit.target.label})` : ''}`; o.style.pointerEvents='auto'; o.style.textAlign='left'; o.onclick=(e)=>{e?.preventDefault?.();e?.stopPropagation?.();e?.stopImmediatePropagation?.();selectTarget(hit.target);}; list.append(o);} overlayRoot.append(list); return true; }
  function refresh(){ if(!rootElement||!overlayRoot)return false; clearOverlayChildren(); for(const t of targets){const rect=t.element?.getBoundingClientRect?.(); if(!rect||rect.width<=0||rect.height<=0) continue; overlayRoot.append(createFrame(rootElement.ownerDocument||globalThis.document,t,rect));} overlayRoot.append(createBadge(rootElement.ownerDocument||globalThis.document)); return true; }
  function isInsideInspectorUi(target){let n=target; while(n){if(n.getAttribute?.('data-ui-inspector-hit-list')==='true'||n.getAttribute?.('data-ui-inspector-hit-option')||n.getAttribute?.('data-ui-inspector-panel')==='true') return true; n=n.parentElement;} return false;}
  function bindCaptureListener(doc){ if(!doc||captureHandler||typeof doc.addEventListener!=='function') return; captureHandler=(e)=>{if(isInsideInspectorUi(e?.target)) return; const x=Number(e?.clientX),y=Number(e?.clientY); if(!Number.isFinite(x)||!Number.isFinite(y)) return; e.preventDefault?.(); e.stopPropagation?.(); e.stopImmediatePropagation?.(); showHitListAtPoint(x,y);}; doc.addEventListener('pointerdown',captureHandler,true); captureHost=doc; }
  function unbindCaptureListener(){ if(captureHost&&captureHandler&&typeof captureHost.removeEventListener==='function') captureHost.removeEventListener('pointerdown',captureHandler,true); captureHost=null; captureHandler=null; }
  function mount(nextRootElement,runtimeOptions={}){ options.onSelect=runtimeOptions.onSelect||options.onSelect; options.onSelectTarget=runtimeOptions.onSelectTarget||options.onSelectTarget; options.onClearSelection=runtimeOptions.onClearSelection||options.onClearSelection; resolveTargetByKey=runtimeOptions.resolveTargetByKey||null; targets=Array.isArray(runtimeOptions.targets)?runtimeOptions.targets:[]; if(!targets.length&&nextRootElement?.querySelectorAll){targets=Array.from(nextRootElement.querySelectorAll(selector)).map((el, i)=>({key:`${el.getAttribute('data-ui-inspector-id')}::${i+1}`,id:el.getAttribute('data-ui-inspector-id'),label:el.getAttribute('data-ui-inspector-id'),element:el}));}
    if(!nextRootElement||typeof nextRootElement.querySelectorAll!=='function') return false; rootElement=nextRootElement; const doc=rootElement.ownerDocument||globalThis.document; const r=ensureOverlayRoot(doc); const host=doc.body||rootElement; if(!r.isConnected) host.append(r); bindCaptureListener(doc); refresh(); return true; }
  function unmount(){ clearSelection(); unbindCaptureListener(); clearOverlayChildren(); overlayRoot?.parentElement?.removeChild(overlayRoot); rootElement=null; targets=[]; return true; }
  return { mount, unmount, refresh, getSelectedId:()=>selectedId, getSelectedTargetKey:()=>selectedTargetKey, getSelectedTarget:()=>selectedTargetKey?(resolveTargetByKey?.(selectedTargetKey)||targets.find((t)=>t.key===selectedTargetKey)||null):null, getOverlayRoot:()=>overlayRoot, select(id, options={}){ const t=options.target||targets.find((x)=>x.id===id); if(!t) return false; return selectTarget(t); }, selectTarget, clearSelection, getHitsAtPoint:(x,y)=>getHitsAtPoint(x,y).map((h)=>({id:h.target.id,key:h.target.key,label:h.target.label})), showHitListAtPoint };
}
