export const MEETING_PARTICIPANT_SOURCE_STAMM = "stamm";
export const MEETING_PARTICIPANT_SOURCE_LOCAL = "projektlokal";

export const MEETING_PARTICIPANT_SOURCES = [
  MEETING_PARTICIPANT_SOURCE_STAMM,
  MEETING_PARTICIPANT_SOURCE_LOCAL,
];

