const PROTOKOLL_UI_EDITOR_ELEMENTS = Object.freeze([
  Object.freeze({
    id: "protokoll.root",
    type: "module",
    role: "root",
    parentId: null,
    order: 0,
    editable: false,
    allowedOps: Object.freeze([]),
    lockedOps: Object.freeze([
      "create",
      "update",
      "delete",
      "save",
      "upload",
      "import",
      "autosave",
      "persist",
      "execute",
      "scan",
      "detect",
      "apply",
    ]),
  }),
  Object.freeze({
    id: "protokoll.header",
    type: "section",
    role: "header",
    parentId: "protokoll.root",
    order: 10,
    editable: false,
    allowedOps: Object.freeze([]),
    lockedOps: Object.freeze([
      "create",
      "update",
      "delete",
      "save",
      "upload",
      "import",
      "autosave",
      "persist",
      "execute",
      "scan",
      "detect",
      "apply",
    ]),
  }),
  Object.freeze({
    id: "protokoll.toolbar",
    type: "section",
    role: "toolbar",
    parentId: "protokoll.root",
    order: 20,
    editable: false,
    allowedOps: Object.freeze([]),
    lockedOps: Object.freeze([
      "create",
      "update",
      "delete",
      "save",
      "upload",
      "import",
      "autosave",
      "persist",
      "execute",
      "scan",
      "detect",
      "apply",
    ]),
  }),
  Object.freeze({
    id: "protokoll.list",
    type: "section",
    role: "list",
    parentId: "protokoll.root",
    order: 30,
    editable: false,
    allowedOps: Object.freeze([]),
    lockedOps: Object.freeze([
      "create",
      "update",
      "delete",
      "save",
      "upload",
      "import",
      "autosave",
      "persist",
      "execute",
      "scan",
      "detect",
      "apply",
    ]),
  }),
  Object.freeze({
    id: "protokoll.detail",
    type: "section",
    role: "detail",
    parentId: "protokoll.root",
    order: 40,
    editable: false,
    allowedOps: Object.freeze([]),
    lockedOps: Object.freeze([
      "create",
      "update",
      "delete",
      "save",
      "upload",
      "import",
      "autosave",
      "persist",
      "execute",
      "scan",
      "detect",
      "apply",
    ]),
  }),
  Object.freeze({
    id: "protokoll.footer",
    type: "section",
    role: "footer",
    parentId: "protokoll.root",
    order: 50,
    editable: false,
    allowedOps: Object.freeze([]),
    lockedOps: Object.freeze([
      "create",
      "update",
      "delete",
      "save",
      "upload",
      "import",
      "autosave",
      "persist",
      "execute",
      "scan",
      "detect",
      "apply",
    ]),
  }),
]);

function cloneElement(element) {
  return {
    ...element,
    allowedOps: [...element.allowedOps],
    lockedOps: [...element.lockedOps],
  };
}

export function getProtokollUiEditorElements() {
  return PROTOKOLL_UI_EDITOR_ELEMENTS.map(cloneElement);
}
