const PROTOKOLL_UI_EDITOR_ELEMENTS = Object.freeze([
  Object.freeze({
    id: "protokoll.root",
    type: "module",
    role: "root",
    parentId: null,
    order: 0,
    editable: false,
    allowedOps: Object.freeze([]),
    lockedOps: Object.freeze([
      "create",
      "update",
      "delete",
      "save",
      "upload",
      "import",
      "autosave",
      "persist",
      "execute",
      "scan",
      "detect",
      "apply",
    ]),
  }),
  Object.freeze({
    id: "protokoll.header",
    type: "section",
    role: "header",
    parentId: "protokoll.root",
    order: 10,
    editable: false,
    allowedOps: Object.freeze([]),
    lockedOps: Object.freeze([
      "create",
      "update",
      "delete",
      "save",
      "upload",
      "import",
      "autosave",
      "persist",
      "execute",
      "scan",
      "detect",
      "apply",
    ]),
  }),
  Object.freeze({
    id: "protokoll.toolbar",
    type: "section",
    role: "toolbar",
    parentId: "protokoll.root",
    order: 20,
    editable: false,
    allowedOps: Object.freeze([]),
    lockedOps: Object.freeze([
      "create",
      "update",
      "delete",
      "save",
      "upload",
      "import",
      "autosave",
      "persist",
      "execute",
      "scan",
      "detect",
      "apply",
    ]),
  }),
  Object.freeze({
    id: "protokoll.list",
    type: "section",
    role: "list",
    parentId: "protokoll.root",
    order: 30,
    editable: false,
    allowedOps: Object.freeze([]),
    lockedOps: Object.freeze([
      "create",
      "update",
      "delete",
      "save",
      "upload",
      "import",
      "autosave",
      "persist",
      "execute",
      "scan",
      "detect",
      "apply",
    ]),
  }),
  Object.freeze({
    id: "protokoll.detail",
    type: "section",
    role: "detail",
    parentId: "protokoll.root",
    order: 40,
    editable: false,
    allowedOps: Object.freeze([]),
    lockedOps: Object.freeze([
      "create",
      "update",
      "delete",
      "save",
      "upload",
      "import",
      "autosave",
      "persist",
      "execute",
      "scan",
      "detect",
      "apply",
    ]),
  }),
  Object.freeze({
    id: "protokoll.topsScreen.quicklane",
    type: "surface",
    role: "quicklane",
    parentId: "protokoll.root",
    order: 45,
    editable: true,
    allowedOps: Object.freeze(["move", "hide", "show"]),
    lockedOps: Object.freeze([
      "create",
      "update",
      "delete",
      "save",
      "upload",
      "import",
      "autosave",
      "persist",
      "execute",
      "scan",
      "detect",
      "apply",
    ]),
  }),
  Object.freeze({
    id: "protokoll.topsScreen.quicklane.group.navigation",
    type: "group",
    role: "navigation",
    parentId: "protokoll.topsScreen.quicklane",
    order: 10,
    editable: true,
    allowedOps: Object.freeze(["move", "hide", "show"]),
    lockedOps: Object.freeze(["delete", "executeTargetAction", "modifyDomainData"]),
  }),
  Object.freeze({
    id: "protokoll.topsScreen.quicklane.pin",
    type: "button",
    role: "navigation-action",
    parentId: "protokoll.topsScreen.quicklane.group.navigation",
    order: 5,
    editable: true,
    allowedOps: Object.freeze(["move", "hide", "show"]),
    lockedOps: Object.freeze(["delete", "executeTargetAction", "modifyDomainData"]),
  }),
  Object.freeze({
    id: "protokoll.topsScreen.quicklane.action.project",
    type: "button",
    role: "navigation-action",
    parentId: "protokoll.topsScreen.quicklane.group.navigation",
    order: 20,
    editable: true,
    allowedOps: Object.freeze(["move", "hide", "show"]),
    lockedOps: Object.freeze(["delete", "executeTargetAction", "modifyDomainData"]),
  }),
  Object.freeze({
    id: "protokoll.topsScreen.quicklane.action.firms",
    type: "button",
    role: "navigation-action",
    parentId: "protokoll.topsScreen.quicklane.group.navigation",
    order: 30,
    editable: true,
    allowedOps: Object.freeze(["move", "hide", "show"]),
    lockedOps: Object.freeze(["delete", "executeTargetAction", "modifyDomainData"]),
  }),
  Object.freeze({
    id: "protokoll.topsScreen.quicklane.action.participants",
    type: "button",
    role: "navigation-action",
    parentId: "protokoll.topsScreen.quicklane.group.navigation",
    order: 40,
    editable: true,
    allowedOps: Object.freeze(["move", "hide", "show"]),
    lockedOps: Object.freeze(["delete", "executeTargetAction", "modifyDomainData"]),
  }),
  Object.freeze({
    id: "protokoll.topsScreen.quicklane.group.visibility",
    type: "group",
    role: "visibility",
    parentId: "protokoll.topsScreen.quicklane",
    order: 20,
    editable: true,
    allowedOps: Object.freeze(["move", "hide", "show"]),
    lockedOps: Object.freeze(["delete", "executeTargetAction", "modifyDomainData"]),
  }),
  Object.freeze({
    id: "protokoll.topsScreen.quicklane.action.ampel",
    type: "button",
    role: "visibility-action",
    parentId: "protokoll.topsScreen.quicklane.group.visibility",
    order: 10,
    editable: true,
    allowedOps: Object.freeze(["move", "hide", "show"]),
    lockedOps: Object.freeze(["delete", "executeTargetAction", "modifyDomainData"]),
  }),
  Object.freeze({
    id: "protokoll.topsScreen.quicklane.action.longtext",
    type: "button",
    role: "visibility-action",
    parentId: "protokoll.topsScreen.quicklane.group.visibility",
    order: 20,
    editable: true,
    allowedOps: Object.freeze(["move", "hide", "show"]),
    lockedOps: Object.freeze(["delete", "executeTargetAction", "modifyDomainData"]),
  }),
  Object.freeze({
    id: "protokoll.topsScreen.quicklane.group.filter",
    type: "group",
    role: "filter",
    parentId: "protokoll.topsScreen.quicklane",
    order: 30,
    editable: true,
    allowedOps: Object.freeze(["move", "hide", "show"]),
    lockedOps: Object.freeze(["delete", "executeTargetAction", "modifyDomainData"]),
  }),
  Object.freeze({
    id: "protokoll.topsScreen.quicklane.action.topFilter",
    type: "button",
    role: "filter-action",
    parentId: "protokoll.topsScreen.quicklane.group.filter",
    order: 10,
    editable: true,
    allowedOps: Object.freeze(["move", "hide", "show"]),
    lockedOps: Object.freeze(["delete", "executeTargetAction", "modifyDomainData"]),
  }),
  Object.freeze({
    id: "protokoll.topsScreen.quicklane.group.output",
    type: "group",
    role: "output",
    parentId: "protokoll.topsScreen.quicklane",
    order: 40,
    editable: true,
    allowedOps: Object.freeze(["move", "hide", "show"]),
    lockedOps: Object.freeze(["delete", "executeTargetAction", "modifyDomainData"]),
  }),
  Object.freeze({
    id: "protokoll.topsScreen.quicklane.action.preview",
    type: "button",
    role: "output-action",
    parentId: "protokoll.topsScreen.quicklane.group.output",
    order: 10,
    editable: true,
    allowedOps: Object.freeze(["move", "hide", "show"]),
    lockedOps: Object.freeze(["delete", "executeTargetAction", "modifyDomainData"]),
  }),
  Object.freeze({
    id: "protokoll.topsScreen.quicklane.action.print",
    type: "button",
    role: "output-action",
    parentId: "protokoll.topsScreen.quicklane.group.output",
    order: 20,
    editable: true,
    allowedOps: Object.freeze(["move", "hide", "show"]),
    lockedOps: Object.freeze(["delete", "executeTargetAction", "modifyDomainData"]),
  }),
  Object.freeze({
    id: "protokoll.topsScreen.quicklane.action.mail",
    type: "button",
    role: "output-action",
    parentId: "protokoll.topsScreen.quicklane.group.output",
    order: 30,
    editable: true,
    allowedOps: Object.freeze(["move", "hide", "show"]),
    lockedOps: Object.freeze(["delete", "executeTargetAction", "modifyDomainData"]),
  }),
  Object.freeze({
    id: "protokoll.footer",
    type: "section",
    role: "footer",
    parentId: "protokoll.root",
    order: 50,
    editable: false,
    allowedOps: Object.freeze([]),
    lockedOps: Object.freeze([
      "create",
      "update",
      "delete",
      "save",
      "upload",
      "import",
      "autosave",
      "persist",
      "execute",
      "scan",
      "detect",
      "apply",
    ]),
  }),
]);

function cloneElement(element) {
  return {
    ...element,
    allowedOps: [...element.allowedOps],
    lockedOps: [...element.lockedOps],
  };
}

export function getProtokollUiEditorElements() {
  return PROTOKOLL_UI_EDITOR_ELEMENTS.map(cloneElement);
}
