const RESTARBEITEN_UI_EDITOR_SCOPE = "restarbeiten.screen";

const LOCKED_LAYOUT_OPS = Object.freeze([
  "show",
  "hide",
  "move",
  "resize",
  "reorder",
  "rename",
  "changeWidth",
  "pin",
  "unpin",
  "reset",
  "applyPreset",
]);

function element({
  id,
  name,
  type,
  role,
  parentId,
  order,
  editable = false,
  allowedOps = ["inspect"],
  lockedOps = LOCKED_LAYOUT_OPS,
  fieldKind,
  actionKind,
  componentKind,
}) {
  return Object.freeze({
    id,
    name,
    type,
    role,
    parentId,
    order,
    visible: true,
    editable,
    allowedOps: Object.freeze([...allowedOps]),
    lockedOps: Object.freeze([...lockedOps]),
    ...(fieldKind ? { fieldKind } : {}),
    ...(actionKind ? { actionKind } : {}),
    ...(componentKind ? { componentKind } : {}),
  });
}

const RESTARBEITEN_UI_EDITOR_ELEMENTS = Object.freeze([
  element({
    id: "restarbeiten.screen.root",
    name: "Restarbeiten",
    type: "root",
    role: "layout",
    parentId: null,
    order: 0,
  }),
  element({
    id: "restarbeiten.screen.filterbar",
    name: "Filterleiste",
    type: "toolbar",
    role: "layout",
    parentId: "restarbeiten.screen.root",
    order: 10,
    componentKind: "filterbar",
  }),
  element({
    id: "restarbeiten.filterbar.group.location",
    name: "Verortung",
    type: "group",
    role: "layout",
    parentId: "restarbeiten.screen.filterbar",
    order: 10,
  }),
  element({
    id: "restarbeiten.filterbar.field.location.level1",
    name: "Verortung 1",
    type: "field",
    role: "meta",
    parentId: "restarbeiten.filterbar.group.location",
    order: 10,
    fieldKind: "select",
  }),
  element({
    id: "restarbeiten.filterbar.field.location.level2",
    name: "Verortung 2",
    type: "field",
    role: "meta",
    parentId: "restarbeiten.filterbar.group.location",
    order: 20,
    fieldKind: "select",
  }),
  element({
    id: "restarbeiten.filterbar.field.location.level3",
    name: "Verortung 3",
    type: "field",
    role: "meta",
    parentId: "restarbeiten.filterbar.group.location",
    order: 30,
    fieldKind: "select",
  }),
  element({
    id: "restarbeiten.filterbar.field.location.level4",
    name: "Verortung 4",
    type: "field",
    role: "meta",
    parentId: "restarbeiten.filterbar.group.location",
    order: 40,
    fieldKind: "select",
  }),
  element({
    id: "restarbeiten.filterbar.group.class",
    name: "Klasse",
    type: "group",
    role: "layout",
    parentId: "restarbeiten.screen.filterbar",
    order: 20,
  }),
  element({
    id: "restarbeiten.filterbar.action.class.all",
    name: "Alle",
    type: "button",
    role: "action",
    parentId: "restarbeiten.filterbar.group.class",
    order: 10,
    actionKind: "filterButton",
  }),
  element({
    id: "restarbeiten.filterbar.action.class.defect",
    name: "Mangel",
    type: "button",
    role: "action",
    parentId: "restarbeiten.filterbar.group.class",
    order: 20,
    actionKind: "filterButton",
  }),
  element({
    id: "restarbeiten.filterbar.action.class.remaining",
    name: "Rest",
    type: "button",
    role: "action",
    parentId: "restarbeiten.filterbar.group.class",
    order: 30,
    actionKind: "filterButton",
  }),
  element({
    id: "restarbeiten.filterbar.group.meta",
    name: "Meta",
    type: "group",
    role: "layout",
    parentId: "restarbeiten.screen.filterbar",
    order: 30,
  }),
  element({
    id: "restarbeiten.filterbar.field.meta.due",
    name: "Fertig bis",
    type: "field",
    role: "date",
    parentId: "restarbeiten.filterbar.group.meta",
    order: 10,
    fieldKind: "select",
  }),
  element({
    id: "restarbeiten.filterbar.field.meta.status",
    name: "Status",
    type: "field",
    role: "status",
    parentId: "restarbeiten.filterbar.group.meta",
    order: 20,
    fieldKind: "select",
  }),
  element({
    id: "restarbeiten.filterbar.field.meta.responsible",
    name: "Verantwortlich",
    type: "field",
    role: "responsible",
    parentId: "restarbeiten.filterbar.group.meta",
    order: 30,
    fieldKind: "select",
  }),
  element({
    id: "restarbeiten.filterbar.field.meta.completed",
    name: "Erledigt",
    type: "field",
    role: "status",
    parentId: "restarbeiten.filterbar.group.meta",
    order: 40,
    fieldKind: "select",
  }),
  element({
    id: "restarbeiten.filterbar.group.close",
    name: "Schliessen",
    type: "group",
    role: "layout",
    parentId: "restarbeiten.screen.filterbar",
    order: 40,
  }),
  element({
    id: "restarbeiten.filterbar.action.close",
    name: "Schliessen",
    type: "button",
    role: "navigation",
    parentId: "restarbeiten.filterbar.group.close",
    order: 10,
    actionKind: "navigationButton",
  }),
]);

function cloneElement(entry) {
  return {
    ...entry,
    allowedOps: [...entry.allowedOps],
    lockedOps: [...entry.lockedOps],
  };
}

export function getRestarbeitenUiEditorElements() {
  return RESTARBEITEN_UI_EDITOR_ELEMENTS.map(cloneElement);
}

export { RESTARBEITEN_UI_EDITOR_SCOPE };
