"use strict";

const { BillingOrderRepository } = require("../../db/billingOrderRepository");

const UUID = /^[0-9a-f]{8}-[0-9a-f]{4}-[1-5][0-9a-f]{3}-[89ab][0-9a-f]{3}-[0-9a-f]{12}$/i;
const HEADER_FIELDS = ["order_number", "order_date", "customer_firm_id", "project_id", "service_reference"];
const POSITION_FIELDS = ["parent_position_id", "type", "position_number", "sort_index", "short_text", "long_text", "quantity", "unit", "unit_price_cents", "is_nep", "vat_rate_percent", "price_input_mode", "price_input_cents"];

function fail(code) {
  const error = new Error(code);
  error.code = code;
  throw error;
}

function inputObject(input, fields) {
  if (!input || typeof input !== "object" || Array.isArray(input)) fail("billing_order_payload_invalid");
  if (input.order_binding_state === "LEGACY_UNRESOLVED" || input.status === "LEGACY_UNRESOLVED") {
    fail("billing_order_legacy_unresolved");
  }
  if (Object.keys(input).some((key) => !fields.includes(key))) fail("billing_order_field_not_allowed");
  return input;
}

function text(value, field, optional = false) {
  if (optional && value == null) return null;
  if (typeof value !== "string" || !value.trim()) fail(`billing_order_${field}_invalid`);
  return value.trim();
}

function id(value) {
  if (typeof value !== "string" || !UUID.test(value)) fail("billing_order_id_invalid");
  return value;
}

function header(input) {
  const result = {};
  for (const field of HEADER_FIELDS) result[field] = text(input[field], field, field === "project_id");
  const date = new Date(`${result.order_date}T00:00:00.000Z`);
  if (!/^\d{4}-\d{2}-\d{2}$/.test(result.order_date) || !Number.isFinite(date.getTime()) || date.toISOString().slice(0, 10) !== result.order_date) {
    fail("billing_order_date_invalid");
  }
  return result;
}

function position(input) {
  const result = { ...input };
  for (const field of ["type", "position_number", "short_text"]) result[field] = text(input[field], field);
  if (!["heading", "service", "note"].includes(result.type)) fail("billing_order_position_type_invalid");
  if (!Number.isSafeInteger(input.sort_index) || input.sort_index < 0) fail("billing_order_sort_index_invalid");
  if (input.parent_position_id != null) id(input.parent_position_id);
  if (input.long_text != null && typeof input.long_text !== "string") fail("billing_order_long_text_invalid");
  if (input.quantity != null && (typeof input.quantity !== "string" || !/^\d+(?:\.\d+)?$/.test(input.quantity) || !Number.isFinite(Number(input.quantity)))) fail("billing_order_quantity_invalid");
  if (input.unit != null) text(input.unit, "unit");
  for (const field of ["unit_price_cents", "price_input_cents", "vat_rate_percent"]) {
    if (input[field] != null && (!Number.isSafeInteger(input[field]) || input[field] < 0)) fail(`billing_order_${field}_invalid`);
  }
  if (input.vat_rate_percent > 100) fail("billing_order_vat_rate_percent_invalid");
  if (input.is_nep != null && ![true, false, 0, 1].includes(input.is_nep)) fail("billing_order_is_nep_invalid");
  if (input.price_input_mode != null && !["NET", "GROSS"].includes(input.price_input_mode)) fail("billing_order_price_input_mode_invalid");
  return result;
}

function validateLv(positions) {
  const ids = new Map(positions.map((entry) => [entry.id, entry]));
  const numbers = new Set();
  const sequence = new Set();
  for (const entry of positions) {
    position(entry);
    if (numbers.has(entry.position_number) || sequence.has(entry.sort_index)) fail("billing_order_position_duplicate");
    numbers.add(entry.position_number);
    sequence.add(entry.sort_index);
    if (entry.parent_position_id) {
      const parent = ids.get(entry.parent_position_id);
      // Earlier parent also excludes cycles without deriving a new LV order.
      if (!parent || parent.sort_index >= entry.sort_index) fail("billing_order_position_parent_invalid");
    }
  }
}

class BillingOrderService {
  #repository;
  #authorize;

  constructor({ repository = new BillingOrderRepository(), authorize = () => require("../../licensing/licenseService").requireFeature("rechnung") } = {}) {
    this.#repository = repository;
    this.#authorize = authorize;
  }

  #load(orderId) {
    const order = this.#repository.get(id(orderId));
    if (!order) fail("billing_order_not_found");
    if (!["DRAFT", "CONFIRMED", "CANCELLED"].includes(order.status) || order.order_binding_state === "LEGACY_UNRESOLVED") fail("billing_order_legacy_unresolved");
    return order;
  }

  #draft(orderId) {
    const order = this.#load(orderId);
    if (order.status !== "DRAFT") fail("billing_order_not_editable");
    return order;
  }

  get(input) {
    this.#authorize();
    return this.#load(inputObject(input, ["id"]).id);
  }

  createDraft(input) {
    this.#authorize();
    // Identities/status are generated by persistence, never accepted from clients.
    return this.#repository.createDraft(header(inputObject(input, HEADER_FIELDS)));
  }

  addPosition(input) {
    this.#authorize();
    const command = inputObject(input, ["id", "position"]);
    const values = position(inputObject(command.position, POSITION_FIELDS));
    return this.#repository.withTransaction(() => {
      const order = this.#draft(command.id);
      validateLv([...order.positions, values]);
      return this.#repository.addPosition(order.id, values);
    });
  }

  confirmOrder(input) {
    this.#authorize();
    const command = inputObject(input, ["id"]);
    return this.#repository.withTransaction(() => {
      const order = this.#draft(command.id);
      header(order);
      validateLv(order.positions);
      if (!order.positions.some((entry) => entry.type === "service")) fail("billing_order_service_position_required");
      return this.#repository.confirmOrder(order.id);
    });
  }
}

let singleton;
function getBillingOrderService() {
  if (!singleton) singleton = new BillingOrderService();
  return singleton;
}

module.exports = { BillingOrderService, getBillingOrderService };
