const TEST_GROUPS = Object.freeze([
  Object.freeze({
    id: "core-protokoll",
    label: "Kern, Protokoll und Projektfirmen",
    includeStoragePathTests: true,
    suites: Object.freeze([
      ["m86-2-2ProtokollAcceptanceSeeder.test.cjs", "runM8622ProtokollAcceptanceSeederTests"],
      ["topsStore.test.cjs", "runTopsStoreTests"],
      ["topsSelectors.test.cjs", "runTopsSelectorsTests"],
      ["topsDtos.test.cjs", "runTopsDtosTests"],
      ["topsCommands.test.cjs", "runTopsCommandsTests"],
      ["topsCloseFlow.test.cjs", "runTopsCloseFlowTests"],
      ["topServiceHierarchy.test.cjs", "runTopServiceHierarchyTests"],
      ["topsActionPolicy.test.cjs", "runTopsActionPolicyTests"],
      ["topsScreen.integration.test.cjs", "runTopsScreenIntegrationTests"],
      ["projectFirmsActiveFlow.test.cjs", "runProjectFirmsActiveFlowTests"],
      ["firmDirectory.test.cjs", "runFirmDirectoryTests"],
      ["firmDirectoryIpc.test.cjs", "runFirmDirectoryIpcTests"],
      ["projectTransferFirmLogic.test.cjs", "runProjectTransferFirmLogicTests"],
      ["projectFirmsLayout.test.cjs", "runProjectFirmsLayoutTests"],
      ["protokollRouterFallback.test.cjs", "runProtokollRouterFallbackTests"],
      ["protokollProjectEntryRouting.test.cjs", "runProtokollProjectEntryRoutingTests"],
      ["protokollUiEditorElements.test.cjs", "runProtokollUiEditorElementsTests"],
    ]),
  }),
  Object.freeze({
    id: "app-modules",
    label: "App-Module",
    suites: Object.freeze([
      ["bbmUiEditorRegistry.test.cjs", "runBbmUiEditorRegistryTests"],
      ["bbmUiEditorDemo.test.cjs", "runBbmUiEditorDemoTests"],
      ["bbmUiEditorInstalledArtifacts.test.cjs", "runBbmUiEditorInstalledArtifactsTests"],
      ["bbmUiEditorRuntimeLauncher.test.cjs", "runBbmUiEditorRuntimeLauncherTests"],
      ["projektverwaltungModule.test.cjs", "runProjektverwaltungModuleTests"],
      ["plaeneModule.test.cjs", "runPlaeneModuleTests"],
      ["restarbeitenDataModel.test.cjs", "runRestarbeitenDataModelTests"],
      ["restarbeitenRules.test.cjs", "runRestarbeitenRulesTests"],
    ]),
  }),
  Object.freeze({
    id: "restarbeiten-module",
    label: "Restarbeiten-Modul",
    suites: Object.freeze([
      ["restarbeitenModule.test.cjs", "runRestarbeitenModuleTests"],
    ]),
  }),
  Object.freeze({
    id: "rechnungen-design",
    label: "Rechnungen UI-Designreferenz",
    suites: Object.freeze([
      ["rechnungenDesignModule.test.cjs", "runRechnungenDesignModuleTests"],
      ["rechnungHeaderRules.test.cjs", "runRechnungHeaderRulesTests"],
      ["rechnungBooking.test.cjs", "runRechnungBookingTests"],
      ["rechnungPdf.test.cjs", "runRechnungPdfTests"],
      ["rechnungCentralCustomers.test.cjs", "runRechnungCentralCustomersTests"],
      ["rechnungPositions.test.cjs", "runRechnungPositionsTests"],
      ["rechnungStammdaten.test.cjs", "runRechnungStammdatenTests"],
      ["rechnungNavigation.test.cjs", "runRechnungNavigationTests"],
      ["rechnungUiEditorUnbounded.test.cjs", "runRechnungUiEditorUnboundedTests"],
      ["rechnungButtonEffectiveGeometry.test.cjs", "runRechnungButtonEffectiveGeometryTests"],
    ]),
  }),
  Object.freeze({
    id: "popup-form-standard",
    label: "Zentraler Popup- und Formularstandard",
    suites: Object.freeze([
      ["popupFormStandard.test.cjs", "runPopupFormStandardTests"],
    ]),
  }),
  Object.freeze({
    id: "editor-core",
    label: "Editor-Kern",
    suites: Object.freeze([
      ["uiEditorContract.test.cjs", "runUiEditorContractTests"],
      ["uiV2EditorV2Rules.test.cjs", "runUiV2EditorV2RulesTests"],
      ["editorLabV2.test.cjs", "runEditorLabV2Tests"],
      ["editorRuntime.catalog.test.cjs", "runEditorRuntimeCatalogTests"],
      ["protokollEditorHostAdapter.test.cjs", "runProtokollEditorHostAdapterTests"],
      ["restarbeitenEditorHostAdapter.test.cjs", "runRestarbeitenEditorHostAdapterTests"],
      ["restarbeitenEditorRegistry.domAnchors.test.cjs", "runRestarbeitenEditorRegistryDomAnchorsTests"],
      ["editorScopeInspector.test.cjs", "runEditorScopeInspectorTests"],
      ["editorBoundary.safety.test.cjs", "runEditorBoundarySafetyTests"],
      ["editorAltVersucheBoundary.test.cjs", "runEditorAltVersucheBoundaryTests"],
      ["editorV2Registry.test.cjs", "runEditorV2RegistryTests"],
      ["editorV2Hover.test.cjs", "runEditorV2HoverTests"],
      ["editorV2Selection.test.cjs", "runEditorV2SelectionTests"],
      ["editorV2Preview.test.cjs", "runEditorV2PreviewTests"],
      ["editorV2Panel.test.cjs", "runEditorV2PanelTests"],
      ["editorLabV2Access.test.cjs", "runEditorLabV2AccessTests"],
    ]),
  }),
  Object.freeze({
    id: "restarbeiten-v2",
    label: "Restarbeiten-V2 und Einstellungen",
    suites: Object.freeze([
      ["restarbeitenV2DevAccess.test.cjs", "runRestarbeitenV2DevAccessTests"],
      ["restarbeitenV2DataContract.test.cjs", "runRestarbeitenV2DataContractTests"],
      ["restarbeitenV2DataSource.test.cjs", "runRestarbeitenV2DataSourceTests"],
      ["restarbeitenV2Mapper.test.cjs", "runRestarbeitenV2MapperTests"],
      ["restarbeitenV2ReadOnlyAdapter.test.cjs", "runRestarbeitenV2ReadOnlyAdapterTests"],
      ["restarbeitenV2LegacyReadBridge.test.cjs", "runRestarbeitenV2LegacyReadBridgeTests"],
      ["restarbeitenV2ReadPathInventory.test.cjs", "runRestarbeitenV2ReadPathInventoryTests"],
      ["restarbeitenV2ReadPathDecision.test.cjs", "runRestarbeitenV2ReadPathDecisionTests"],
      ["restarbeitenV2ReadOnlyDataSourceFactory.test.cjs", "runRestarbeitenV2ReadOnlyDataSourceFactoryTests"],
      ["homeView.test.cjs", "runHomeViewTests"],
      ["projectSettingsIpc.test.cjs", "runProjectSettingsIpcTests"],
      ["settingsUserProfileSource.test.cjs", "runSettingsUserProfileSourceTests"],
      ["settingsPrintLayout.test.cjs", "runSettingsPrintLayoutTests"],
    ]),
  }),
  Object.freeze({
    id: "layout-output",
    label: "Tabellenlayout, Ausgabe und Dienste",
    suites: Object.freeze([
      ["tableLayoutEditorPrototype.test.cjs", "runTableLayoutEditorPrototypeTests"],
      ["printUserDataResolver.test.cjs", "runPrintUserDataResolverTests"],
      ["printOrientation.test.cjs", "runPrintOrientationTests"],
      ["printModes.test.cjs", "runPrintModesTests"],
      ["printTableLayouts.test.cjs", "runPrintTableLayoutsTests"],
      ["m85PdfSatzvertrag.test.cjs", "runM85PdfSatzvertragTests"],
      ["tableLayoutsResolver.test.cjs", "runTableLayoutsResolverTests"],
      ["tableLayoutsRepo.test.cjs", "runTableLayoutsRepoTests"],
      ["tableLayoutsIpc.test.cjs", "runTableLayoutsIpcTests"],
      ["tableLayoutRegistry.test.cjs", "runTableLayoutRegistryTests"],
      ["layoutToolsRegression.test.cjs", "runLayoutToolsRegressionTests"],
      ["layoutToolsAutoDetection.test.cjs", "runLayoutToolsAutoDetectionTests"],
      ["sendMailPayload.test.cjs", "runSendMailPayloadTests"],
      ["ausgabeModule.test.cjs", "runAusgabeModuleTests"],
      ["audioModule.test.cjs", "runAudioModuleTests"],
      ["dictionaryModule.test.cjs", "runDictionaryModuleTests"],
      ["drucklayoutModule.test.cjs", "runDrucklayoutModuleTests"],
      ["distCustomerBuild.test.cjs", "runDistCustomerBuildTests"],
    ]),
  }),
  Object.freeze({
    id: "licensing-native",
    label: "Lizenzierung und native Laufzeit",
    suites: Object.freeze([
      ["licenseTrialRuntime.test.cjs", "runLicenseTrialRuntimeTests"],
      ["licenseStorageBootstrap.test.cjs", "runLicenseStorageBootstrapTests"],
      ["licenseRequest.test.cjs", "runLicenseRequestTests"],
      ["licenseDoubleClickImport.test.cjs", "runLicenseDoubleClickImportTests"],
      ["licenseFeatureGuards.test.cjs", "runLicenseFeatureGuardTests"],
      ["licenseStandardFeatures.test.cjs", "runLicenseStandardFeaturesTests"],
      ["featureGuardEnforcement.test.cjs", "runFeatureGuardEnforcementTests"],
      ["licensePresentation.test.cjs", "runLicensePresentationTests"],
      ["developmentLicenseProvider.test.cjs", "runDevelopmentLicenseProviderTests"],
      ["nativeTestRuntime.test.cjs", "runNativeTestRuntimeTests"],
    ]),
  }),
  Object.freeze({
    id: "ui-editor-m51-m80",
    label: "UI-Editor M51 bis M80.2 und Harness",
    suites: Object.freeze([
      ["m51UiEditorKitIntegration.test.cjs", "runM51UiEditorKitIntegrationTests"],
      ["m52UiEditorVisibleEntry.test.cjs", "runM52UiEditorVisibleEntryTests"],
      ["m54UiElementRefs.test.cjs", "runM54UiElementRefsTests"],
      ["m55UiElementSelection.test.cjs", "runM55UiElementSelectionTests"],
      ["m56PersistentSelectionFrame.test.cjs", "runM56PersistentSelectionFrameTests"],
      ["m59KitSelectionRuntimeIntegration.test.cjs", "runM59KitSelectionRuntimeIntegrationTests"],
      ["m60KitRuntimeStandard.test.cjs", "runM60KitRuntimeStandardTests"],
      ["m62BbmSelectionLegacyCleanup.test.cjs", "runM62BbmSelectionLegacyCleanupTests"],
      ["m63aEditorIntegrationAudit.test.cjs", "runM63aEditorIntegrationAuditTests"],
      ["m63bReadonlyInspectorBridge.test.cjs", "runM63bReadonlyInspectorBridgeTests"],
      ["m63cLayoutControlConsole.test.cjs", "runM63cLayoutControlConsoleTests"],
      ["m63cRealRegistryPanelIntegration.test.cjs", "runM63cRealRegistryPanelIntegrationTests"],
      ["m64UiEditorTestSurface.test.cjs", "runM64UiEditorTestSurfaceTests"],
      ["m65LayoutPersistenceRoundtrip.test.cjs", "runM65LayoutPersistenceRoundtripTests"],
      ["m66ResetLayoutToDefaults.test.cjs", "runM66ResetLayoutToDefaultsTests"],
      ["m67ResetElementToDefaults.test.cjs", "runM67ResetElementToDefaultsTests"],
      ["m80ElectronUiEditor.test.cjs", "runM80ElectronUiEditorTests"],
      ["m80-1RegistrationRefresh.test.cjs", "runM801RegistrationRefreshTests"],
      ["m80-2HeaderEditboxLayout.test.cjs", "runM802HeaderEditboxLayoutTests"],
      ["m81BbmPdfAdapter.test.cjs", "runM81BbmPdfAdapterTests"],
      ["m81-1ProfileRestore.test.cjs", "runM811ProfileRestoreTests"],
      ["m82AppStarterPackage.test.cjs", "runM82AppStarterPackageTests"],
      ["m82-1BbmFeintuning.test.cjs", "runM821BbmFeintuningTests"],
      ["m82-2BbmGeometryRisks.test.cjs", "runM822BbmGeometryRiskTests"],
      ["m82-3BbmSpacerCompactUi.test.cjs", "runM823BbmSpacerCompactUiTests"],
      ["m82-4BbmTableColumnEditing.test.cjs", "runM824BbmTableColumnEditingTests"],
      ["m82-5BbmSimpleEditorMode.test.cjs", "runM825BbmSimpleEditorModeTests"],
      ["m82-6TopScreenModuleClosure.test.cjs", "runM826TopScreenModuleClosureTests"],
      ["m82-7RemainingIndicators.test.cjs", "runM827RemainingIndicatorTests"],
      ["m82-7-2GenericTextResize.test.cjs", "runM8272GenericTextResizeTests"],
      ["m82-7-3TextResizeCurrentValue.test.cjs", "runM8273TextResizeCurrentValueTests"],
      ["m82-7-4AmpelEditing.test.cjs", "runM8274AmpelEditingTests"],
      ["m82-7-5LayoutPersistenceMetaElements.test.cjs", "runM8275LayoutPersistenceMetaElementsTests"],
      ["m83-0ComponentContracts.test.cjs", "runM830ComponentContractTests"],
      ["m86-3EditorStartMetaRepair.test.cjs", "runM863EditorStartMetaRepairTests"],
      ["m86-4GlobalClickBlocker.test.cjs", "runM864GlobalClickBlockerTests"],
      ["m86-5ProtokollLayoutRepair.test.cjs", "runM865ProtokollLayoutRepairTests"],
      ["m86-7ProtokollButtonContracts.test.cjs", "runM867ProtokollButtonContractTests"],
      ["m86-8ProtokollFullContract.test.cjs", "runM868ProtokollFullContractTests"],
      ["m86-9ProtokollMetaTargetContract.test.cjs", "runM869ProtokollMetaTargetContractTests"],
      ["m86-10ProtokollOriginalThreeColumnContract.test.cjs", "runM8610ProtokollOriginalThreeColumnContractTests"],
      ["m86-11ProtokollRestarbeitenRowGeometry.test.cjs", "runM8611ProtokollRestarbeitenRowGeometryTests"],
      ["m86-11bProtokollProductiveTableStructure.test.cjs", "runM8611bProtokollProductiveTableStructureTests"],
      ["m86-12ProtokollSourceGridRuntime.test.cjs", "runM8612ProtokollSourceGridRuntimeTests"],
      ["m86-14GlobalLayoutRestore.test.cjs", "runM8614GlobalLayoutRestoreTests"],
      ["m86-15UniversalEditorContract.test.cjs", "runM8615UniversalEditorContractTests"],
      ["m86-16RealEditorRuntime.test.cjs", "runM8616RealEditorRuntimeTests"],
      ["m86-21RestarbeitenViewport.test.cjs", "runM8621RestarbeitenViewportTests"],
      ["m86-22EditorMarkerCleanup.test.cjs", "runM8622EditorMarkerCleanupTests"],
      ["m86-23SaveCloseAcknowledgement.test.cjs", "runM8623SaveCloseAcknowledgementTests"],
      ["m86-24VisibleEditorAcceptance.test.cjs", "runM8624VisibleEditorAcceptanceTests"],
      ["uiEditorAcceptanceIsolation.test.cjs", "runUiEditorAcceptanceIsolationTests"],
      ["testHarnessOrchestration.test.cjs", "runTestHarnessOrchestrationTests"],
    ]),
  }),
]);

function findTestGroup(groupId) {
  return TEST_GROUPS.find((group) => group.id === groupId) || null;
}

module.exports = { TEST_GROUPS, findTestGroup };
