export function createEditorLabRegistry() {
  return [
    {
      id: "editorlab.root",
      label: "EditorLab",
      kind: "frame",
      editable: false,
      ops: ["move", "resize", "hide"],
      selector: '[data-ui-v2-id="editorlab.root"]',
    },
    {
      id: "editorlab.header",
      label: "Header",
      kind: "frame",
      parentId: "editorlab.root",
      editable: true,
      ops: ["move", "resize", "hide"],
      selector: '[data-ui-v2-id="editorlab.header"]',
    },
    {
      id: "editorlab.header.titleGroup",
      label: "Titelgruppe",
      kind: "frame",
      parentId: "editorlab.header",
      editable: true,
      ops: ["move", "resize", "hide"],
      selector: '[data-ui-v2-id="editorlab.header.titleGroup"]',
    },
    {
      id: "editorlab.header.searchGroup",
      label: "Such-/Filtergruppe",
      kind: "frame",
      parentId: "editorlab.header",
      editable: true,
      ops: ["move", "resize", "hide"],
      selector: '[data-ui-v2-id="editorlab.header.searchGroup"]',
    },
    {
      id: "editorlab.header.statusGroup",
      label: "Statusgruppe",
      kind: "frame",
      parentId: "editorlab.header",
      editable: true,
      ops: ["move", "resize", "hide"],
      selector: '[data-ui-v2-id="editorlab.header.statusGroup"]',
    },
    {
      id: "editorlab.quicklane",
      label: "Quicklane",
      kind: "frame",
      parentId: "editorlab.root",
      editable: true,
      ops: ["move", "resize", "hide"],
      selector: '[data-ui-v2-id="editorlab.quicklane"]',
    },
    {
      id: "editorlab.quicklane.lock",
      label: "Vorhaengeschloss",
      kind: "control",
      parentId: "editorlab.quicklane",
      editable: false,
      ops: ["move", "hide"],
      selector: '[data-ui-v2-id="editorlab.quicklane.lock"]',
    },
    {
      id: "editorlab.quicklane.new",
      label: "Button Neu",
      kind: "control",
      parentId: "editorlab.quicklane",
      editable: false,
      ops: ["move", "hide"],
      selector: '[data-ui-v2-id="editorlab.quicklane.new"]',
    },
    {
      id: "editorlab.quicklane.save",
      label: "Button Speichern",
      kind: "control",
      parentId: "editorlab.quicklane",
      editable: false,
      ops: ["move", "hide"],
      selector: '[data-ui-v2-id="editorlab.quicklane.save"]',
    },
    {
      id: "editorlab.quicklane.view",
      label: "Button Ansicht",
      kind: "control",
      parentId: "editorlab.quicklane",
      editable: false,
      ops: ["move", "hide"],
      selector: '[data-ui-v2-id="editorlab.quicklane.view"]',
    },
    {
      id: "editorlab.main",
      label: "Main",
      kind: "frame",
      parentId: "editorlab.root",
      editable: true,
      ops: ["move", "resize", "hide"],
      selector: '[data-ui-v2-id="editorlab.main"]',
    },
    {
      id: "editorlab.main.groupA",
      label: "Gruppe A",
      kind: "frame",
      parentId: "editorlab.main",
      editable: true,
      ops: ["move", "resize", "hide"],
      selector: '[data-ui-v2-id="editorlab.main.groupA"]',
    },
    {
      id: "editorlab.main.groupA.fieldA1",
      label: "Feld A1",
      kind: "field",
      parentId: "editorlab.main.groupA",
      editable: true,
      ops: ["move", "resize", "hide"],
      selector: '[data-ui-v2-id="editorlab.main.groupA.fieldA1"]',
    },
    {
      id: "editorlab.main.groupA.buttonA2",
      label: "Button A2",
      kind: "control",
      parentId: "editorlab.main.groupA",
      editable: false,
      ops: ["move", "hide"],
      selector: '[data-ui-v2-id="editorlab.main.groupA.buttonA2"]',
    },
    {
      id: "editorlab.main.groupB",
      label: "Gruppe B",
      kind: "frame",
      parentId: "editorlab.main",
      editable: true,
      ops: ["move", "resize", "hide"],
      selector: '[data-ui-v2-id="editorlab.main.groupB"]',
    },
    {
      id: "editorlab.main.groupB.fieldB1",
      label: "Feld B1",
      kind: "field",
      parentId: "editorlab.main.groupB",
      editable: true,
      ops: ["move", "resize", "hide"],
      selector: '[data-ui-v2-id="editorlab.main.groupB.fieldB1"]',
    },
    {
      id: "editorlab.main.groupB.buttonB2",
      label: "Button B2",
      kind: "control",
      parentId: "editorlab.main.groupB",
      editable: false,
      ops: ["move", "hide"],
      selector: '[data-ui-v2-id="editorlab.main.groupB.buttonB2"]',
    },
    {
      id: "editorlab.footer",
      label: "Footer",
      kind: "frame",
      parentId: "editorlab.root",
      editable: true,
      ops: ["move", "resize", "hide"],
      selector: '[data-ui-v2-id="editorlab.footer"]',
    },
    {
      id: "editorlab.footer.groupC",
      label: "Gruppe C",
      kind: "frame",
      parentId: "editorlab.footer",
      editable: true,
      ops: ["move", "resize", "hide"],
      selector: '[data-ui-v2-id="editorlab.footer.groupC"]',
    },
    {
      id: "editorlab.footer.groupC.fieldC1",
      label: "Feld C1",
      kind: "field",
      parentId: "editorlab.footer.groupC",
      editable: true,
      ops: ["move", "resize", "hide"],
      selector: '[data-ui-v2-id="editorlab.footer.groupC.fieldC1"]',
    },
    {
      id: "editorlab.footer.groupD",
      label: "Gruppe D",
      kind: "frame",
      parentId: "editorlab.footer",
      editable: true,
      ops: ["move", "resize", "hide"],
      selector: '[data-ui-v2-id="editorlab.footer.groupD"]',
    },
    {
      id: "editorlab.footer.groupD.fieldD1",
      label: "Feld D1",
      kind: "field",
      parentId: "editorlab.footer.groupD",
      editable: true,
      ops: ["move", "resize", "hide"],
      selector: '[data-ui-v2-id="editorlab.footer.groupD.fieldD1"]',
    },
    {
      id: "editorlab.footer.groupD.buttonD2",
      label: "Button D2",
      kind: "control",
      parentId: "editorlab.footer.groupD",
      editable: false,
      ops: ["move", "hide"],
      selector: '[data-ui-v2-id="editorlab.footer.groupD.buttonD2"]',
    },
  ];
}

