export const PROJECT_COMPANY_SOURCE_STAMM = "stamm";
export const PROJECT_COMPANY_SOURCE_LOCAL = "projektlokal";

export const PROJECT_COMPANY_SOURCES = [
  PROJECT_COMPANY_SOURCE_STAMM,
  PROJECT_COMPANY_SOURCE_LOCAL,
];

